---
# Source: health-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: health-srv-health-service
  labels:
    helm.sh/chart: health-service-0.1.0
    app.kubernetes.io/name: health-service
    app.kubernetes.io/instance: health-srv
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: health-service
    app.kubernetes.io/instance: health-srv
---
# Source: health-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-srv-health-service
  labels:
    helm.sh/chart: health-service-0.1.0
    app.kubernetes.io/name: health-service
    app.kubernetes.io/instance: health-srv
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: health-service
      app.kubernetes.io/instance: health-srv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: health-service
        app.kubernetes.io/instance: health-srv
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: health-service
          securityContext:
            {}
          image: "alxbird/otus-ms-arch:1.0.0-health"
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_UP
              value: "true"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
          resources:
            {}
---
# Source: health-service/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-srv-health-service
  labels:
    helm.sh/chart: health-service-0.1.0
    app.kubernetes.io/name: health-service
    app.kubernetes.io/instance: health-srv
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: "arch.homework"
      http:
        paths:
          - path: /otusapp/alex-v/?(.*)
            pathType: Prefix
            backend:
              service:
                name: health-srv-health-service
                port:
                  number: 80
